"""
import_asdm.py — ms_import_asdm

Converts a raw ASDM directory to a CASA Measurement Set.

Fixed parameters (not exposed — scientifically motivated defaults):
  ocorr_mode='co'     Cross-correlations only; auto-correlations dropped.
  savecmds=True       Online flags written to <ms_name>.flagonline.txt.
  applyflags=False    Online flags are NOT applied during import.
                      ms_apply_preflag owns all flagging in a single auditable pass.
  asis='ExecBlock'    Copies the ASDM ExecBlock table into the MS as the
                      ASDM_EXECBLOCK subtable. Its configName is the array
                      configuration, which the MS schema has no column for.

The tool always writes import_asdm.py to workdir. When execute=True it also
runs importasdm in-process and returns the resolved ms_path and online_flag_file.
"""

from __future__ import annotations

from pathlib import Path

from ms_create.exceptions import ASDMNotFoundError, ImportFailedError
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_inspect.util.stage_log import record_stage

TOOL_NAME = "ms_import_asdm"


def _resolve_ms_name(asdm_path: Path, ms_name: str, workdir: Path) -> Path:
    stem = ms_name if ms_name else asdm_path.stem
    if not stem.endswith(".ms"):
        stem = stem + ".ms"
    return workdir / stem


def _build_script(
    asdm_str: str,
    ms_str: str,
    flag_file_str: str,
    with_pointing_correction: bool,
    workdir: str = "",
) -> str:
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_import_asdm (ms_create).
Run with: python import_asdm.py
\"\"\"
from casatasks import importasdm

{record}

asdm_path = {asdm_str!r}
ms_path = {ms_str!r}
online_flag_file = {flag_file_str!r}

importasdm(
    asdm=asdm_path,
    vis=ms_path,
    ocorr_mode="co",
    with_pointing_correction={with_pointing_correction},
    savecmds=True,
    outfile=online_flag_file,
    applyflags=False,
    overwrite=False,
    asis="ExecBlock",
)
# The MS this writes is the input to every later stage, and the loop learns
# where it is from this stage alone — so the raising form, and record the
# online flag file too: preflag reads it and a silent absence there surfaces
# much later as "no flags were applied".
_record_stage({workdir!r}, "import_asdm", ms_path)
_record_stage({workdir!r}, "import_asdm", online_flag_file)
print(f"Import complete: {{ms_path}}")
print(f"Online flags saved: {{online_flag_file}}")
"""


def run(
    asdm_path: str,
    workdir: str,
    ms_name: str = "",
    with_pointing_correction: bool = False,
    execute: bool = False,
) -> dict:
    """
    Convert a raw ASDM to a CASA Measurement Set.

    Args:
        asdm_path:                Path to the ASDM directory.
        workdir:                  Existing output directory.
        ms_name:                  Output MS filename (default: <asdm_stem>.ms).
        with_pointing_correction: Apply pointing correction during import.
                                  Expensive on large datasets; default False.
        execute:                  If False (default), write script and return.
                                  If True, run importasdm in-process.

    Returns:
        Standard response envelope. Always includes script_path, ms_path
        (resolved), and online_flag_file. When execute=False, ms_path and
        online_flag_file carry UNAVAILABLE flags.
    """
    asdm = Path(asdm_path)
    if not asdm.exists():
        raise ASDMNotFoundError(
            f"ASDM not found: {asdm_path}",
            ms_path=asdm_path,
        )
    if not asdm.is_dir():
        raise ASDMNotFoundError(
            f"ASDM path is not a directory: {asdm_path}",
            ms_path=asdm_path,
        )

    workdir_path = Path(workdir)
    if not workdir_path.is_dir():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=asdm_path,
        )

    ms_out = _resolve_ms_name(asdm, ms_name, workdir_path)
    flag_file = ms_out.with_suffix(".flagonline.txt")
    script_path = workdir_path / "import_asdm.py"

    script_content = _build_script(
        str(asdm),
        str(ms_out),
        str(flag_file),
        with_pointing_correction,
        workdir=str(workdir_path),
    )
    script_path.write_text(script_content)

    casa_calls: list[str] = [f"write_script → {script_path}"]
    warnings: list[str] = []

    base_data: dict = {
        "script_path": fmt_field(str(script_path)),
        "asdm_path": fmt_field(str(asdm)),
        "ms_path": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
        "online_flag_file": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
        "ocorr_mode": fmt_field("co"),
        "with_pointing_correction": fmt_field(with_pointing_correction),
        "savecmds": fmt_field(True),
        "applyflags": fmt_field(False),
        "asis": fmt_field("ExecBlock"),
    }

    if not execute:
        warnings.append(
            f"Script written to {script_path}. Run import_asdm.py externally, "
            "then call ms_verify_import to confirm the MS and online flag file."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=asdm_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run in-process
    try:
        from casatasks import importasdm  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=asdm_path,
        ) from None

    if ms_out.exists():
        warnings.append(
            f"Output MS already exists at {ms_out} — importasdm will raise. "
            "Delete or rename the existing MS before re-running with execute=True."
        )

    casa_calls.append(
        f"casatasks.importasdm(asdm='{asdm}', vis='{ms_out}', ocorr_mode='co', "
        f"savecmds=True, applyflags=False, asis='ExecBlock')"
    )
    try:
        importasdm(
            asdm=str(asdm),
            vis=str(ms_out),
            ocorr_mode="co",
            with_pointing_correction=with_pointing_correction,
            savecmds=True,
            outfile=str(flag_file),
            applyflags=False,
            overwrite=False,
            asis="ExecBlock",
        )
    except Exception as exc:
        raise ImportFailedError(
            f"importasdm failed: {exc}",
            ms_path=asdm_path,
        ) from exc

    record_stage(str(workdir_path), "import_asdm", str(ms_out))
    record_stage(str(workdir_path), "import_asdm", str(flag_file))

    base_data["ms_path"] = fmt_field(str(ms_out))
    base_data["online_flag_file"] = fmt_field(str(flag_file))

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=asdm_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
