"""
applycal.py — ms_applycal

Apply calibration tables to a single field selection, writing the result
to the CORRECTED_DATA column. Called once per field category (flux cal,
phase cal, target) with different gainfield and interp parameters each time.

CASA call sequence:
  applycal(vis, field, gaintable, gainfield, interp, calwt, applymode,
           parang, flagbackup)

When execute=False (default), writes a self-contained script to
workdir/applycal_<field_stem>.py and returns immediately.

The three-call pattern for a standard observation:
  ms_applycal(field=flux_field,  gainfield=[..., flux_field],  interp=[..., 'nearest'])
  ms_applycal(field=phase_field, gainfield=[..., phase_field], interp=[..., 'nearest'])
  ms_applycal(field=target,      gainfield=[..., phase_field], interp=[..., 'linear'])
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import (
    describe_numeric_fields,
    open_table,
    validate_ms_path,
)
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, response_envelope
from ms_inspect.util.stage_log import record_stage
from ms_modify.exceptions import ApplycalFailedError

TOOL_NAME = "ms_applycal"


def _script_path(workdir: Path, field: str) -> Path:
    stem = field.replace(",", "_").replace(" ", "_").replace("/", "_")[:40]
    return workdir / f"applycal_{stem}.py"


def _build_script(
    ms_str: str,
    workdir: str,
    field: str,
    gaintable: list[str],
    gainfield: list[str],
    interp: list[str],
    calwt: bool,
    applymode: str,
    parang: bool,
    flagbackup: bool,
    spwmap: list[list[int]] | None = None,
) -> str:
    # spwmap is omitted entirely when not supplied → CASA default (identity).
    spwmap_line = f"    spwmap={spwmap!r},\n" if spwmap is not None else ""
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record
    from ms_inspect.util.stage_log import TABLE_PROBE_SNIPPET as probe

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_applycal (ms_modify).
Applies calibration to field: {field!r}
\"\"\"
from casatasks import applycal

{record}
{probe}

applycal(
    vis={ms_str!r},
    field={field!r},
    gaintable={gaintable!r},
    gainfield={gainfield!r},
    interp={interp!r},
{spwmap_line}    calwt={calwt},
    applymode={applymode!r},
    parang={parang},
    flagbackup={flagbackup},
)
# applycal returns None, so completion has to be measured rather than read
# off a return value: the column it exists to populate is either there or not.
_corrected = "CORRECTED_DATA" in _table_colnames({ms_str!r})
_record_stage(
    {workdir!r},
    "applycal",
    {ms_str!r},
    {{"field": {field!r}, "corrected_data": _corrected}},
)
if not _corrected:
    raise RuntimeError(
        "applycal returned but CORRECTED_DATA is not present on "
        + {ms_str!r}
        + " — the stage did not do what it exists to do."
    )
print("Done. CORRECTED_DATA populated for field: {field}")
"""


def run(
    ms_path: str,
    field: str,
    gaintable: list[str],
    workdir: str,
    gainfield: list[str] | None = None,
    interp: list[str] | None = None,
    spwmap: list[list[int]] | None = None,
    calwt: bool = False,
    applymode: str = "calonly",
    parang: bool = True,
    flagbackup: bool = False,
    execute: bool = False,
) -> dict:
    """
    Apply calibration tables to a field and write CORRECTED_DATA.

    Args:
        ms_path:    Path to the Measurement Set.
        field:      CASA field selection to apply calibration to.
        gaintable:  Ordered list of caltable paths to apply.
        workdir:    Existing directory; script is written here.
        gainfield:  Per-table field selection for which solutions to use.
                    Default: [''] * len(gaintable) (use all solutions in each table).
        interp:     Per-table interpolation mode. Use 'nearest' for calibrators,
                    'linear' for the target, 'nearest,nearestflag' for delay tables.
                    Default: ['linear'] * len(gaintable).
        spwmap:     Optional per-table SPW map (list-of-lists aligned to gaintable),
                    e.g. [[], [0,0,0,0], []] to fan an spw-combined table (entry 1)
                    across all SPWs while leaving per-SPW tables on identity. Default
                    None → CASA identity mapping (no change to per-SPW behaviour).
                    Only needed when a table was solved with combine='spw' (a VLA
                    multiband-delay choice); not telescope-general.
        calwt:      Calibrate the weights (default False — VLA weights are not
                    properly normalised; use statwt before imaging instead).
        applymode:  'calonly' (default) applies calibration without flagging, so
                    post-calibration RFI flagging (ms_postcal_flag, skill 13) owns the
                    FLAG column. Use 'calflagstrict' to additionally flag data with
                    missing/flagged solutions at apply time.
        parang:     Apply parallactic angle correction (default True).
        flagbackup: Save a flag backup before applying (default False; set True
                    for the first applycal call on the flux calibrator).
        execute:    If False (default), write script and return.
                    If True, run applycal in-process.

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes corrected_written flag.
    """
    field = normalize_field_sel(field)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []
    warnings.extend(describe_numeric_fields(ms_path, field))

    if gainfield is None:
        gainfield = [""] * len(gaintable)
    if interp is None:
        interp = ["linear"] * len(gaintable)

    if len(gainfield) != len(gaintable):
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"gainfield length ({len(gainfield)}) must match gaintable length ({len(gaintable)})",
            ms_path=ms_path,
        )

    if len(interp) != len(gaintable):
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"interp length ({len(interp)}) must match gaintable length ({len(gaintable)})",
            ms_path=ms_path,
        )

    if spwmap is not None and len(spwmap) != len(gaintable):
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"spwmap length ({len(spwmap)}) must match gaintable length ({len(gaintable)}). "
            "Pass a per-table list-of-lists, e.g. [[], [0,0,0,0], []].",
            ms_path=ms_path,
        )

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    for gt in gaintable:
        if not Path(gt).exists():
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                f"Caltable not found: {gt}",
                ms_path=ms_path,
            )

    script = _script_path(workdir_path, field)
    script.write_text(
        _build_script(
            ms_str=ms_str,
            workdir=str(workdir_path),
            field=field,
            gaintable=gaintable,
            gainfield=gainfield,
            interp=interp,
            calwt=calwt,
            applymode=applymode,
            parang=parang,
            flagbackup=flagbackup,
            spwmap=spwmap,
        )
    )
    casa_calls.append(f"write_script → {script}")

    if not execute:
        warnings.append(
            f"Script written to {script}. Run it externally. "
            "Inspect CORRECTED_DATA on calibrators before applying to the target."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data={
                "script_path": fmt_field(str(script)),
                "corrected_written": fmt_field(
                    False, flag="UNAVAILABLE", note="script not yet executed"
                ),
                "field": field,
                "n_tables": len(gaintable),
                "applymode": applymode,
                "calwt": calwt,
                "parang": parang,
                "flagbackup": flagbackup,
            },
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True
    try:
        from casatasks import applycal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.applycal(field={field!r}, n_tables={len(gaintable)}, "
        f"applymode={applymode!r}) → CORRECTED_DATA"
    )

    try:
        applycal_kwargs: dict = dict(
            vis=ms_str,
            field=field,
            gaintable=gaintable,
            gainfield=gainfield,
            interp=interp,
            calwt=calwt,
            applymode=applymode,
            parang=parang,
            flagbackup=flagbackup,
        )
        if spwmap is not None:
            applycal_kwargs["spwmap"] = spwmap
        applycal(**applycal_kwargs)
    except Exception as e:
        raise ApplycalFailedError(
            f"applycal raised an exception: {e}\n"
            f"Command: applycal(vis={ms_str!r}, field={field!r}, "
            f"n_tables={len(gaintable)}, applymode={applymode!r})",
            ms_path=ms_path,
        ) from e

    # applycal returns None; a clean return proves only that it did not raise.
    # Measure the column instead of trusting the return.
    with open_table(ms_str) as tb:
        corrected_written = "CORRECTED_DATA" in set(tb.colnames())
    record_stage(
        str(workdir_path),
        "applycal",
        ms_str,
        {"field": field, "corrected_data": corrected_written},
    )
    if not corrected_written:
        raise ApplycalFailedError(
            f"applycal returned but CORRECTED_DATA is not present on {ms_str!r} — "
            "the stage did not do what it exists to do.",
            ms_path=ms_path,
        )

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data={
            "script_path": fmt_field(str(script)),
            "corrected_written": fmt_field(corrected_written),
            "field": field,
            "n_tables": len(gaintable),
            "applymode": applymode,
            "calwt": calwt,
            "parang": parang,
            "flagbackup": flagbackup,
        },
        warnings=warnings,
        casa_calls=casa_calls,
    )
