"""
initial_bandpass.py — ms_initial_bandpass

Produces an initial coarse bandpass calibration on a calibrator-only MS
and populates the CORRECTED column so that rflag can proceed.

CASA call sequence (adapted from evla_pipe/stages/initial_bp.py):

  Step 1 — gaincal(solint='int', calmode='p')  → init_gain.g
  Step 2 — bandpass(solint='inf', combine='scan', fillgaps=62) → BP0.b
  Step 3 — applycal(applycal_field, applymode) → CORRECTED written on applycal_field

Hard fails if either caltable is not produced on disk.

When execute=False (default), always writes a self-contained Python script to
workdir/initial_bandpass.py and returns immediately. The user runs the script
externally; ms_verify_caltables can then confirm the outputs.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_spw_sel, response_envelope
from ms_inspect.util.stage_log import record_stage
from ms_modify.exceptions import InitialBandpassFailedError

TOOL_NAME = "ms_initial_bandpass"

# Fixed parameters matching evla_pipe defaults — not exposed to caller
_MINSNR = 3.0
_FILLGAPS = 62
_SOLNORM = False


def _table_exists(path: str) -> bool:
    """Return True if a caltable directory exists and is non-empty."""
    p = Path(path)
    return p.exists() and p.is_dir() and any(p.iterdir())


def _build_script(
    ms_str: str,
    workdir: str,
    init_gain_table: str,
    bp_table: str,
    bp_field: str,
    applycal_field: str,
    ref_ant: str,
    bp_scan: str,
    all_spw: str,
    priorcals: list[str],
    min_bl_per_ant: int,
    uvrange: str,
    applymode: str,
) -> str:
    """Return a self-contained Python script that runs the bandpass calibration."""
    uvrange_line = (
        f'    gaincal_kwargs["uvrange"] = "{uvrange}"\n    bandpass_kwargs["uvrange"] = "{uvrange}"\n'
        if uvrange
        else ""
    )
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record
    from ms_modify.pathguard import SAFE_RM_TABLE_SNIPPET as safe_rm

    priorcals_repr = repr(priorcals)
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_initial_bandpass (ms_modify).
Run with: python initial_bandpass.py
\"\"\"
import os
import shutil
from casatasks import gaincal, bandpass, applycal

ms_str = {ms_str!r}
init_gain_table = {init_gain_table!r}
bp_table = {bp_table!r}
priorcals = {priorcals_repr}

{safe_rm}
{record}
workdir = {workdir!r}

_safe_rm_table(init_gain_table)
_safe_rm_table(bp_table)

# Step 1 — gaincal (phase, per-integration)
gaincal_kwargs = dict(
    vis=ms_str,
    caltable=init_gain_table,
    field={bp_field!r},
    spw={all_spw!r},
    scan={bp_scan!r},
    solint="int",
    refant={ref_ant!r},
    minblperant={min_bl_per_ant},
    minsnr={_MINSNR},
    gaintype="G",
    calmode="p",
    solnorm={_SOLNORM},
    gaintable=priorcals,
)
{uvrange_line}gaincal(**gaincal_kwargs)
_record_stage(workdir, "initial_bandpass", init_gain_table)

# Step 2 — bandpass (solint=inf, combine='scan')
bp_gaintable = priorcals + [init_gain_table]
bandpass_kwargs = dict(
    vis=ms_str,
    caltable=bp_table,
    field={bp_field!r},
    spw={all_spw!r},
    scan={bp_scan!r},
    solint="inf",
    combine="scan",
    refant={ref_ant!r},
    minblperant={min_bl_per_ant},
    minsnr={_MINSNR},
    bandtype="B",
    fillgaps={_FILLGAPS},
    solnorm={_SOLNORM},
    gaintable=bp_gaintable,
)
bandpass(**bandpass_kwargs)
_record_stage(workdir, "initial_bandpass", bp_table)

# Step 3 — applycal: solutions are solved on bp_field but applied to
# applycal_field (decoupled so the caller controls which field(s) receive
# CORRECTED — applying bp_field solutions onto unrelated fields makes CASA
# extrapolate them in time and can heavily flag mid-session scans).
applycal_gaintable = priorcals + [init_gain_table, bp_table]
n_tables = len(applycal_gaintable)
applycal(
    vis=ms_str,
    field={applycal_field!r},
    spw={all_spw!r},
    gaintable=applycal_gaintable,
    calwt=[False] * n_tables,
    applymode={applymode!r},
    flagbackup=True,
)
_record_stage(workdir, "initial_bandpass", ms_str)
print("Done. CORRECTED column populated on applycal_field.")
"""


def run(
    ms_path: str,
    bp_field: str,
    applycal_field: str,
    ref_ant: str,
    workdir: str,
    bp_scan: str = "",
    all_spw: str = "",
    priorcals: list[str] | None = None,
    min_bl_per_ant: int = 4,
    uvrange: str = "",
    applymode: str = "calflagstrict",
    target_fields: str = "",
    execute: bool = False,
) -> dict:
    """
    Solve an initial coarse bandpass and populate the CORRECTED column.

    Args:
        ms_path:        Path to cal_only.ms.
        bp_field:       CASA field selection string for bandpass calibrator
                        (used for the gaincal + bandpass solves).
        applycal_field: CASA field selection string for the Step 3 applycal.
                        Required, no default. Gains were solved on bp_field only,
                        so normally pass the bandpass calibrator field here; pass
                        '' (all fields) only deliberately.
        ref_ant:        Reference antenna name (from ms_refant output).
        workdir:        Directory to write caltables into (must exist).
        bp_scan:        CASA scan selection string (empty = all scans).
        all_spw:        CASA SpW selection string (empty = all SpWs).
        priorcals:      Prior calibration tables to pre-apply (e.g. requantiser, Tsys).
        min_bl_per_ant: minblperant for gaincal and bandpass (default 4).
        uvrange:        UV range restriction: the uvrange in the ms_field_list
                        warning for this field (for example 3C84 at L band).
        applymode:      applycal mode for Step 3 (default 'calflagstrict').
                        Fall back to 'calflag' if strict flagging is too aggressive.
        target_fields:  Optional CASA field selection for the science-target /
                        transfer fields, used only for the SpW-coverage guardrail.
                        Empty (default) infers them from intents; the tool raises
                        if it cannot, so pass them explicitly when intents are absent.
        execute:        If False (default), write script and return immediately.
                        If True, run CASA calibration in-process (may take minutes).

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes init_gain_table, bp_table, corrected_written.
    """
    all_spw = normalize_spw_sel(all_spw)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    if priorcals is None:
        priorcals = []

    # ------------------------------------------------------------------
    # Validate workdir and priorcals
    # ------------------------------------------------------------------
    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    for pc in priorcals:
        if not Path(pc).exists():
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                f"Prior calibration table not found: {pc}",
                ms_path=ms_path,
            )

    # SpW-coverage guardrail: warn if the bandpass solve field does not carry the
    # SpWs the science target / transfer fields need (raises if the target cannot
    # be inferred from intents and target_fields was not supplied).
    from ms_inspect.util.spw_coverage import check_spw_coverage

    warnings.extend(check_spw_coverage(ms_str, bp_field, all_spw, target_fields))

    init_gain_table = str(workdir_path / "init_gain.g")
    bp_table = str(workdir_path / "BP0.b")
    script_path = str(workdir_path / "initial_bandpass.py")

    # ------------------------------------------------------------------
    # Always write script
    # ------------------------------------------------------------------
    script_content = _build_script(
        ms_str=ms_str,
        workdir=str(workdir_path),
        init_gain_table=init_gain_table,
        bp_table=bp_table,
        bp_field=bp_field,
        applycal_field=applycal_field,
        ref_ant=ref_ant,
        bp_scan=bp_scan,
        all_spw=all_spw,
        priorcals=priorcals,
        min_bl_per_ant=min_bl_per_ant,
        uvrange=uvrange,
        applymode=applymode,
    )
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    # ------------------------------------------------------------------
    # execute=False: return immediately with script path
    # ------------------------------------------------------------------
    if not execute:
        data = {
            "script_path": fmt_field(script_path),
            "init_gain_table": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
            "bp_table": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
            "corrected_written": fmt_field(False),
            "ref_ant": ref_ant,
            "bp_field": bp_field,
            "applycal_field": applycal_field,
            "applymode": applymode,
            "solint_phase": "int",
            "solint_bp": "inf",
            "fillgaps": _FILLGAPS,
            "min_bl_per_ant": min_bl_per_ant,
        }
        if uvrange:
            data["uvrange"] = uvrange
        warnings.append(
            f"Script written to {script_path}. Run it externally, "
            "then call ms_verify_caltables to confirm outputs."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # ------------------------------------------------------------------
    # execute=True: import casatasks and run
    # ------------------------------------------------------------------
    try:
        from casatasks import applycal, bandpass, gaincal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    # ------------------------------------------------------------------
    # Step 1 — gaincal (phase, per-integration)
    # ------------------------------------------------------------------
    gaincal_kwargs: dict = dict(
        vis=ms_str,
        caltable=init_gain_table,
        field=bp_field,
        spw=all_spw,
        scan=bp_scan,
        solint="int",
        refant=ref_ant,
        minblperant=min_bl_per_ant,
        minsnr=_MINSNR,
        gaintype="G",
        calmode="p",
        solnorm=_SOLNORM,
        gaintable=priorcals,
    )
    if uvrange:
        gaincal_kwargs["uvrange"] = uvrange

    casa_calls.append(
        f"casatasks.gaincal(field='{bp_field}', solint='int', calmode='p', "
        f"refant='{ref_ant}') → init_gain.g"
    )

    try:
        gaincal(**gaincal_kwargs)
    except Exception as e:
        raise InitialBandpassFailedError(
            f"gaincal failed with exception: {e}\n"
            f"Command: gaincal(vis='{ms_str}', caltable='{init_gain_table}', "
            f"field='{bp_field}', solint='int', refant='{ref_ant}')",
            ms_path=ms_path,
        ) from e

    # record_stage does the existence check and writes the stage-log line either
    # way; the domain error is re-raised over it so the caller keeps the
    # diagnostic message rather than a bare RuntimeError.
    try:
        record_stage(str(workdir_path), "initial_bandpass", init_gain_table)
    except RuntimeError as exc:
        raise InitialBandpassFailedError(
            f"gaincal did not produce init_gain.g at '{init_gain_table}'. "
            "Possible causes: too few unflagged baselines, wrong field/scan selection, "
            f"or refant '{ref_ant}' not present in the MS.",
            ms_path=ms_path,
        ) from exc

    # ------------------------------------------------------------------
    # Step 2 — bandpass (solint=inf, combine='scan')
    # ------------------------------------------------------------------
    bp_gaintable = priorcals + [init_gain_table]

    bandpass_kwargs: dict = dict(
        vis=ms_str,
        caltable=bp_table,
        field=bp_field,
        spw=all_spw,
        scan=bp_scan,
        solint="inf",
        combine="scan",
        refant=ref_ant,
        minblperant=min_bl_per_ant,
        minsnr=_MINSNR,
        bandtype="B",
        fillgaps=_FILLGAPS,
        solnorm=_SOLNORM,
        gaintable=bp_gaintable,
    )
    if uvrange:
        bandpass_kwargs["uvrange"] = uvrange

    casa_calls.append(
        f"casatasks.bandpass(field='{bp_field}', solint='inf', combine='scan', "
        f"fillgaps={_FILLGAPS}, refant='{ref_ant}') → BP0.b"
    )

    try:
        bandpass(**bandpass_kwargs)
    except Exception as e:
        raise InitialBandpassFailedError(
            f"bandpass failed with exception: {e}\n"
            f"Command: bandpass(vis='{ms_str}', caltable='{bp_table}', "
            f"field='{bp_field}', solint='inf', combine='scan', refant='{ref_ant}')",
            ms_path=ms_path,
        ) from e

    # record_stage does the existence check and writes the stage-log line either
    # way; the domain error is re-raised over it so the caller keeps the
    # diagnostic message rather than a bare RuntimeError.
    try:
        record_stage(str(workdir_path), "initial_bandpass", bp_table)
    except RuntimeError as exc:
        raise InitialBandpassFailedError(
            f"bandpass did not produce BP0.b at '{bp_table}'. "
            "Possible causes: too few unflagged solutions, wrong field/scan selection, "
            f"or init_gain.g was produced but contained no valid solutions.",
            ms_path=ms_path,
        ) from exc

    # ------------------------------------------------------------------
    # Step 3 — applycal (bandpass calibrator only)
    # ------------------------------------------------------------------
    # Solutions are solved on bp_field but applied to applycal_field. The caller
    # controls which field(s) receive CORRECTED: applying bp_field solutions onto
    # other fields makes CASA extrapolate them in time onto those scans, and for
    # EBs where bp_field is observed mid-session those scans can get ~90% flagged.
    # flagbackup=True ensures this inspection step can never silently flag.
    applycal_gaintable = priorcals + [init_gain_table, bp_table]
    n_tables = len(applycal_gaintable)

    casa_calls.append(
        f"casatasks.applycal(field={applycal_field!r}, gaintable=[...{n_tables} tables], "
        f"calwt=[False]*{n_tables}, applymode={applymode!r}) → CORRECTED on applycal_field"
    )

    try:
        applycal(
            vis=ms_str,
            field=applycal_field,
            spw=all_spw,
            gaintable=applycal_gaintable,
            calwt=[False] * n_tables,
            applymode=applymode,
            flagbackup=True,
        )
    except Exception as e:
        warnings.append(
            f"applycal raised an exception: {e}. CORRECTED column may not be fully populated."
        )
        corrected_written = False
    else:
        corrected_written = True
        # Step 3 completing is what makes the stage complete: bp_table alone is
        # written at step 2, so a stage log carrying only that would report the
        # stage done while CORRECTED was never populated. The MS always exists,
        # so this line cannot raise — it records that step 3 returned.
        record_stage(str(workdir_path), "initial_bandpass", ms_str)

    # ------------------------------------------------------------------
    # Build response
    # ------------------------------------------------------------------
    data = {
        "script_path": fmt_field(script_path),
        "init_gain_table": fmt_field(init_gain_table),
        "bp_table": fmt_field(bp_table),
        "corrected_written": fmt_field(corrected_written),
        "n_prior_tables": len(priorcals),
        "ref_ant": ref_ant,
        "bp_field": bp_field,
        "applycal_field": applycal_field,
        "applymode": applymode,
        "solint_phase": "int",
        "solint_bp": "inf",
        "fillgaps": _FILLGAPS,
        "min_bl_per_ant": min_bl_per_ant,
    }
    if uvrange:
        data["uvrange"] = uvrange

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
