"""
initial_rflag.py — ms_apply_initial_rflag

Runs rflag + tfcrop on the residual column (CORRECTED − MODEL) after the
initial bandpass has been applied and CORRECTED is populated.

Why two direct calls (not flagdata mode='list'):
- CASA 6.7.5 raises `KeyError 'nreport'` in the list-mode report-aggregation
  path after the flags are computed (notably when an agent's report is empty),
  aborting the call. This bit two separate reduction runs (G55, HH 1-2), both
  of which fell back to a hand-written two-call script.
- So we issue two explicit `flagdata(action='apply')` passes — rflag then
  tfcrop — preceded by a single `flagmanager(mode='save')`. Single agent per
  call, no report merge, no list-mode aggregation.

Script output:
  workdir/initial_rflag.py — self-contained driver script
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import open_table, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_inspect.util.stage_log import record_stage

TOOL_NAME = "ms_apply_initial_rflag"

_FLAG_VERSION = "before_initial_rflag"


def _build_script(
    ms_str: str,
    field: str,
    timedevscale: float,
    freqdevscale: float,
    timecutoff: float,
    freqcutoff: float,
    workdir: str = "",
) -> str:
    """Return a self-contained initial_rflag Python script.

    field selection is mandatory. Residual rflag is only meaningful on fields
    whose CORRECTED column is genuinely calibrated at the point of the call.
    Running it over fields with no valid solutions yet flags almost everything
    (their CORRECTED-MODEL residual is dominated by uncorrected gain/phase error,
    not RFI). The caller (skill) decides which field is valid at each stage.
    """
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_apply_initial_rflag (ms_modify).
Run with: python initial_rflag.py

Requires: CORRECTED and MODEL columns populated (run initial_bandpass.py first).

Two direct flagdata passes (rflag then tfcrop) rather than one mode='list'
pass: CASA 6.7.5 aborts list mode with KeyError 'nreport'. A single
flagmanager save captures the pre-flag state; flagbackup=False on both passes
avoids redundant per-call backups.
\"\"\"
from casatasks import flagdata, flagmanager

{record}

ms_path = {ms_str!r}
field = {field!r}

# One versioned backup of the pre-rflag FLAG state.
flagmanager(vis=ms_path, mode="save", versionname={_FLAG_VERSION!r})

# Pass 1: rflag on the residual column.
flagdata(
    vis=ms_path,
    mode="rflag",
    field=field,
    datacolumn="residual",
    timedevscale={timedevscale},
    freqdevscale={freqdevscale},
    action="apply",
    flagbackup=False,
)

# Pass 2: tfcrop on the residual column.
flagdata(
    vis=ms_path,
    mode="tfcrop",
    field=field,
    datacolumn="residual",
    timecutoff={timecutoff},
    freqcutoff={freqcutoff},
    action="apply",
    flagbackup=False,
)
# flagdata(action='apply') returns nothing useful, so completion is measured
# with a summary pass. It reports the flagged fraction the stage produced —
# a number, not a verdict — so a pass that flagged nothing is visible in the
# record instead of looking identical to one that worked.
_summary = flagdata(vis={ms_str!r}, mode="summary")
_flagged = (
    float(_summary["flagged"]) / float(_summary["total"]) if _summary.get("total") else None
)
_record_stage({workdir!r}, "initial_rflag", {ms_str!r}, {{"flagged_fraction": _flagged}})
print("Initial rflag + tfcrop complete.")
print("Use ms_flag_summary to inspect the flag delta,")
print("and ms_residual_stats to verify the residual distribution.")
"""


def run(
    ms_path: str,
    workdir: str,
    field: str,
    timedevscale: float = 5.0,
    freqdevscale: float = 5.0,
    timecutoff: float = 4.0,
    freqcutoff: float = 4.0,
    execute: bool = False,
) -> dict:
    """
    Generate (and optionally execute) initial rflag + tfcrop on residuals.

    Args:
        ms_path:      Path to the MS (CORRECTED + MODEL must exist).
        workdir:      Existing directory for the generated script.
        field:        REQUIRED. The field selection to flag. Must be scoped to the
                      field(s) whose CORRECTED column is genuinely calibrated at the
                      point of the call (the caller decides which — e.g. the bandpass
                      calibrator right after initial_bandpass, or all calibrators after
                      the full solve + applycal). An all-field pass over uncalibrated
                      fields flags ~90% of the data and is recoverable only by
                      re-splitting. The tool only enforces that a field is given.
        timedevscale: rflag time deviation threshold (default 5.0).
        freqdevscale: rflag frequency deviation threshold (default 5.0).
        timecutoff:   tfcrop time deviation threshold (default 4.0).
        freqcutoff:   tfcrop frequency deviation threshold (default 4.0).
        execute:      If False (default), write the script and return.
                      If True, run the two flagdata passes in-process.

    Returns:
        Standard response envelope. Always includes script_path.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    script_path = str(workdir_path / "initial_rflag.py")

    if not field or not str(field).strip():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            "field is required. Scope residual rflag to the field(s) whose CORRECTED "
            "column is valid at this stage. An all-field pass over uncalibrated fields "
            "flags ~90% of the data and is recoverable only by re-splitting.",
            ms_path=ms_path,
        )

    # This tool always flags datacolumn='residual' (CORRECTED − MODEL); that
    # computation is meaningless without MODEL_DATA. Refuse before CASA does.
    with open_table(ms_str) as tb:
        if "MODEL_DATA" not in set(tb.colnames()):
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                "MODEL_DATA column not present. Models may have been written "
                "virtually (usescratch=False), which writes no MODEL_DATA column; "
                "re-run setjy with usescratch=True to materialize it.",
                ms_path=ms_path,
            )

    # Always write the script
    script_content = _build_script(
        ms_str,
        field,
        timedevscale,
        freqdevscale,
        timecutoff,
        freqcutoff,
        workdir=str(workdir_path),
    )
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "script_path": fmt_field(script_path),
        "field": fmt_field(field),
        "rflag_timedevscale": timedevscale,
        "rflag_freqdevscale": freqdevscale,
        "tfcrop_timecutoff": timecutoff,
        "tfcrop_freqcutoff": freqcutoff,
        "datacolumn": "residual",
    }

    if not execute:
        warnings.append(
            f"Script written to {workdir}. "
            "Ensure initial_bandpass.py has been run first (CORRECTED + MODEL must exist). "
            "Then run initial_rflag.py externally and call ms_flag_summary to capture the delta."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run in-process — two direct passes, not mode='list'
    try:
        from casatasks import flagdata, flagmanager  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    from ms_inspect.exceptions import ComputationError

    try:
        casa_calls.append(f"flagmanager(mode='save', versionname={_FLAG_VERSION!r})")
        flagmanager(vis=ms_str, mode="save", versionname=_FLAG_VERSION)

        casa_calls.append(
            f"flagdata(mode='rflag', field={field!r}, datacolumn='residual', action='apply')"
        )
        flagdata(
            vis=ms_str,
            mode="rflag",
            field=field,
            datacolumn="residual",
            timedevscale=timedevscale,
            freqdevscale=freqdevscale,
            action="apply",
            flagbackup=False,
        )

        casa_calls.append(
            f"flagdata(mode='tfcrop', field={field!r}, datacolumn='residual', action='apply')"
        )
        flagdata(
            vis=ms_str,
            mode="tfcrop",
            field=field,
            datacolumn="residual",
            timecutoff=timecutoff,
            freqcutoff=freqcutoff,
            action="apply",
            flagbackup=False,
        )
    except Exception as exc:
        raise ComputationError(
            f"initial rflag/tfcrop failed: {exc}",
            ms_path=ms_path,
        ) from exc

    # flagdata(action='apply') returns nothing useful, so measure the flagged
    # fraction the pass produced instead of asserting that it worked.
    summary = flagdata(vis=ms_str, mode="summary")
    total = float(summary.get("total") or 0.0)
    flagged_fraction = float(summary["flagged"]) / total if total else None
    record_stage(
        str(workdir_path),
        "initial_rflag",
        ms_str,
        {"flagged_fraction": flagged_fraction},
    )

    base_data["flags_applied"] = fmt_field(True)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
