"""
preflag.py — ms_apply_preflag

Applies deterministic pre-calibration flags in a single flagdata list-mode
pass, then splits calibrator fields to workdir/calibrators.ms.

Flagging steps (order matters — all combined in preflag_cmds.txt):
  1. Online flags from importasdm .flagonline.txt (if provided)
  2. Shadow flags (mode='shadow', tolerance=shadow_tolerance_m)
  3. Zero-amplitude clip (mode='clip', clipzeros=True)
  4. Conservative tfcrop (mode='tfcrop', timecutoff=3.0, freqcutoff=3.0)
  5. Extend flags across polarizations (mode='extend', extendpols=True)

All five run via flagdata(mode='list', inpfile=preflag_cmds.txt, flagbackup=True)
in a single atomic pass. After flagging, calibrator fields are split to
workdir/calibrators.ms with keepflags=False.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, response_envelope
from ms_inspect.util.stage_log import record_stage

TOOL_NAME = "ms_apply_preflag"


def _build_cmds_content(
    online_flag_file: str,
    shadow_tolerance_m: float,
    do_tfcrop: bool,
) -> str:
    """
    Build the text content for preflag_cmds.txt.

    Each line is a flagdata command in key=value format (flagdata list-mode
    syntax). Online flag file lines are prepended verbatim if provided.
    """
    lines: list[str] = []

    if online_flag_file:
        p = Path(online_flag_file)
        if p.exists():
            raw = p.read_text()
            # Include non-empty, non-comment lines verbatim
            for line in raw.splitlines():
                stripped = line.strip()
                if stripped and not stripped.startswith("#"):
                    lines.append(stripped)
        else:
            lines.append(f"# WARNING: online_flag_file not found: {online_flag_file}")

    lines.append(f"mode='shadow' tolerance={shadow_tolerance_m}")
    lines.append("mode='clip' clipzeros=True")
    if do_tfcrop:
        lines.append("mode='tfcrop' timecutoff=3.0 freqcutoff=3.0")
    lines.append("mode='extend' extendpols=True")

    return "\n".join(lines) + "\n"


def _build_script(
    ms_str: str,
    cmds_path: str,
    cal_ms: str,
    cal_fields: str,
    workdir: str = "",
) -> str:
    """Return a self-contained preflag + split Python script."""
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_apply_preflag (ms_modify).
Run with: python preflag.py
\"\"\"
from casatasks import flagdata, split

{record}

ms_path = {ms_str!r}
cmds_file = {cmds_path!r}
cal_ms = {cal_ms!r}
cal_fields = {cal_fields!r}

# Step 1 — Apply all deterministic pre-calibration flags in one pass.
# flagbackup=True saves a versioned copy automatically.
flagdata(
    vis=ms_path,
    mode="list",
    inpfile=cmds_file,
    flagbackup=True,
)
# Step 1's own product is a changed FLAG column, so measure the fraction it
# produced rather than record that the call returned.
_summary = flagdata(vis=ms_path, mode="summary")
_flagged = (
    float(_summary["flagged"]) / float(_summary["total"]) if _summary.get("total") else None
)
_record_stage({workdir!r}, "preflag", ms_path, {{"flagged_fraction": _flagged}})
print("Preflagging done.")

# Step 2 — Split calibrator fields to calibrators.ms.
# keepflags=False drops flagged rows so downstream calibration never sees them.
split(
    vis=ms_path,
    outputvis=cal_ms,
    field=cal_fields,
    datacolumn="data",
    keepflags=False,
)
# calibrators.ms IS a new product, so this line uses the raising form: every
# later calibration stage runs against it, and a split that produced nothing
# must stop here rather than surface as a confusing failure two stages on.
_record_stage({workdir!r}, "preflag", cal_ms)
print(f"Calibrator split complete: {{cal_ms}}")
"""


def run(
    ms_path: str,
    workdir: str,
    cal_fields: str,
    online_flag_file: str = "",
    shadow_tolerance_m: float = 0.0,
    do_tfcrop: bool = True,
    execute: bool = False,
) -> dict:
    """
    Apply deterministic pre-calibration flags and split calibrators.

    Args:
        ms_path:           Path to the full MS.
        workdir:           Existing output directory.
        cal_fields:        CASA field selection string for calibrators (required).
        online_flag_file:  Path to .flagonline.txt from importasdm (empty = skip).
        shadow_tolerance_m: Shadow tolerance in metres (default 0.0).
        do_tfcrop:         Apply conservative tfcrop pass (default True).
        execute:           If False (default), write scripts and return.
                           If True, run flagdata + split in-process.

    Returns:
        Standard response envelope. Always includes cmds_path and script_path.
        When execute=True, also includes flags_applied and cal_ms.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    cal_fields = normalize_field_sel(cal_fields)
    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    cmds_path = str(workdir_path / "preflag_cmds.txt")
    script_path = str(workdir_path / "preflag.py")
    cal_ms = str(workdir_path / "calibrators.ms")

    # Always write the flag command list
    cmds_content = _build_cmds_content(online_flag_file, shadow_tolerance_m, do_tfcrop)
    Path(cmds_path).write_text(cmds_content)
    casa_calls.append(f"write_cmds → {cmds_path}")

    n_cmd_lines = len(
        [ln for ln in cmds_content.splitlines() if ln.strip() and not ln.startswith("#")]
    )

    # Always write the script
    script_content = _build_script(ms_str, cmds_path, cal_ms, cal_fields, workdir=str(workdir_path))
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "cmds_path": fmt_field(cmds_path),
        "script_path": fmt_field(script_path),
        "n_flag_commands": fmt_field(n_cmd_lines),
        "cal_fields": cal_fields,
        "do_tfcrop": do_tfcrop,
        "shadow_tolerance_m": shadow_tolerance_m,
        "online_flag_file": online_flag_file or None,
        "cal_ms": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
    }

    if not execute:
        warnings.append(
            f"Scripts written to {workdir}. Run preflag.py externally, "
            "then call ms_flag_summary to assess the flag delta."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run in-process
    try:
        from casatasks import flagdata, split  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(f"casatasks.flagdata(mode='list', inpfile='{cmds_path}', flagbackup=True)")
    try:
        flagdata(
            vis=ms_str,
            mode="list",
            inpfile=cmds_path,
            flagbackup=True,
        )
    except Exception as exc:
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"flagdata(mode='list') failed: {exc}",
            ms_path=ms_path,
        ) from exc

    casa_calls.append(
        f"casatasks.split(field='{cal_fields}', outputvis='{cal_ms}', "
        f"datacolumn='data', keepflags=False)"
    )
    try:
        split(
            vis=ms_str,
            outputvis=cal_ms,
            field=cal_fields,
            datacolumn="data",
            keepflags=False,
        )
    except Exception as exc:
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"split to calibrators.ms failed: {exc}",
            ms_path=ms_path,
        ) from exc

    # flagdata(action='apply') returns nothing useful, so measure the flagged
    # fraction the pass produced instead of asserting that it worked.
    summary = flagdata(vis=ms_str, mode="summary")
    total = float(summary.get("total") or 0.0)
    flagged_fraction = float(summary["flagged"]) / total if total else None
    record_stage(
        str(workdir_path),
        "preflag",
        ms_str,
        {"flagged_fraction": flagged_fraction},
    )

    record_stage(str(workdir_path), "preflag", cal_ms)
    base_data["flags_applied"] = fmt_field(True)
    base_data["cal_ms"] = fmt_field(cal_ms)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
